download-maven-plugin/pom.xml, download-maven-plugin/src/it/GetAndUnpack/pom.xml, download-maven-plugin/src/it/basicGet/pom.xml, download-maven-plugin/src/it/basicGetWithSignature/pom.xml, download-maven-plugin/src/it/basicGetWrongSignature/pom.xml, download-maven-plugin/src/main/java/com/googlecode/Artifact.java, download-maven-plugin/src/main/java/com/googlecode/DownloadCache.java, download-maven-plugin/src/main/java/com/googlecode/WGet.java
download-maven-plugin easily breaks with multiple threads builds (-T option), or with multiple builds running in parallel.
For example the plugin will often fail on ci (bamboo, jenkins, etc) servers with EOFException (DownloadCache.loadIndex(DownloadCache.java:105)) or IOException "Failed to copy full contents from …" (DownloadCache.install(DownloadCache.java:95)).
Some projects would fail >50% of builds due to the lack safe concurrent file operations.
These concerns are also raised by https://github.com/maven-download-plugin/maven-download-plugin/issues/2
This pull request solves these problems by using FileLocks and Java7's nio enhancements.
Copying files is done "safely" with Files.copy(..), and load and saving the cache index file is down with FileLocks.
Some extras
- Java7 …
=> multi-thread and multi-build safe (filelocks around io operations)

download-maven-plugin/src/main/java/com/googlecode/Artifact.java
UnArchiver expect the output folder to exist. This is the behavior in the WGet goal.
=> Creating outputDirectory if not exists for Archive goal

download-maven-plugin/src/main/java/com/googlecode/CachedFileEntry.java, download-maven-plugin/src/main/java/com/googlecode/DownloadCache.java, download-maven-plugin/src/main/java/com/googlecode/WGet.java
There are two possible scenarios which may lead to false cache hit:
1: Multiple modules download files with the same name from different sources
2: Same module downloads a file from different urls, but with the same file name.
In this case cache was hit because of file name even though url has changed.
Please see the test at 78d02cfa9762e9e410fc9ad6936be0bbdacdb2a2 Let me know if the test is valuable, I will include it into PR
=> Fix false cache hit

download-maven-plugin/pom.xml
Errors and warnings encountered when running `mvn -Pits clean verify`:
- Added `install` goal (and `localRepositoryPath` configuration) for `maven-invoker-plugin`. Without this goal, the ITs are run against the SNAPSHOT version downloaded from the snapshot repository rather than the local built version.
- Using `environmentVariables` to pass the `testing.versionUnderTest` property to the IT POMs, rather than `mavenOpts`; as the latter fails if someone has `MAVEN_OPTS` defined in a `.mavenrc` file.
- Added version to the `maven-invoker-plugin` to avoid Maven warning.
- Using `${project.version}` rather than `${version}` to avoid Maven warning.
=> Fixes IT run issues on some environments

.gitignore, download-maven-plugin/src/main/java/com/googlecode/WGet.java
Now if maven runs in `--batch-mode` then no download progress appears.
NOTE: `maven-invoker-plugin` always runs child builds in batch mode, so from now you will not see download progress regardless of mode.
=> #52 Wget honors batch mode

download-maven-plugin/pom.xml, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/SignatureUtils.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/cache/DownloadCache.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/cache/FileBackedIndex.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/cache/FileIndex.java, download-maven-plugin/src/test/java/com/googlecode/download/maven/plugin/internal/cache/FileBackedIndexTest.java
#72 Start `DownloadCache` refactoring
The main reason - separation of concerns.
Benefit - understandable and maintainable code, which is easy to test with unit test.
Done - extracted Index management code from the Cache.
ToBeDone (next) - separate signature management code from the cache.
@mickaelistria please, take a look and tell what do you think?
=> #72 Start DownloadCache refactoring

download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/Artifact.java
The `WGet` mojo allows an execution to be skipped.
The need for skipping is not unique to `wget`, it is equally as important for `artifact`.
This PR implements the skip option for `artifact`.
=> Add skip property to artifact mojo

download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
Small change to allow using the plugin from the command line to download and unpack a zip file.
This is going to be useful in systems that have Maven but don't have unzip installed (such as Jenkins nodes).
=> allow unpacking from command-line

src/main/java/com/googlecode/download/maven/plugin/internal/Artifact.java
Fixes the bug in #100. Also, fix two typos in `Artifact.java`.
=> #100 Artifact: also create outputDirectory when copying (not unpacking)

src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
Given the pom config:
```xml
<plugin>
<groupId>com.googlecode.maven-download-plugin</groupId>
<artifactId>download-maven-plugin</artifactId>
<executions>
<execution>
<id>autodeploy-dashboard-xar</id>
<phase>generate-test-resources</phase>
<goals>
<goal>wget</goal>
</goals>
<configuration>
<url>http://data.exist-db.org/spatial/os-mastermap-topography-layer-sample-data.gz</url>
<readTimeOut>120000</readTimeOut>
<sha1>ca14a6dafcdec4cbe9bbadcf65fa1e245665c0e5</sha1>
<checkSignature>true</checkSignature>
<unpack>true</unpack>
<outputDirectory>${project.build.testOutputDirectory}</outputDirectory>
</configuration>
</execution>
</executions>
</plugin>
```
I would get an error like:
```
ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.2-SNAPSHOT:wget …
```
=> Fix an issue with unpacking gzip files

src/it/indexRetroCompatibility/invoke.properties, src/it/indexRetroCompatibility/pom.xml, src/it/indexRetroCompatibility/verify.groovy, src/main/java/com/googlecode/download/maven/plugin/internal/cache/FileBackedIndex.java, src/main/java/com/googlecode/download/maven/plugin/internal/cache/IncompatibleIndexException.java
When reading an index created with an older version of the Plugin,
deserialization errors may rise, due to breaking changes introduced in
newer versions.
Such an index should be droppped (as unreadable) and a new one created
instead, using the new storage strategy.
To test this behavior, a new [Integration test](src/it/indexRetroCompatibility/invoke.properties) have been introduced:
* download a file with version 1.3.0 (creating an index based on the
previous storage strategy)
* download a file with the current version (build should not break)
Should fix #120 .
=> Fix Cache index retro-compatibility

pom.xml
fixes #139
fixes #137
This also upgrades another vulnerable transitive dependency (commons-compress)
=> #139 Upgrade plexus-archiver since old one has security vulnerability

pom.xml, src/main/java/com/googlecode/download/maven/plugin/internal/Artifact.java
fixes #138
This rises the bar for maven to 3.x
=> #138 Upgrade maven-core since old one depends on vulnerable com.jcraft:jsch:0.1.23

src/it/alwaysOverwrite/pom.xml
The verification step fails under Groovy 2.4.x and 2.5.x, because Groovy tries to access internal Java file APIs which are no longer accessible by default on JDK 16, when using File.exists(). Upgrading from `groovy-all:2.4.4` to `groovy:3.0.8` fixes the issue.
BTW, Maven site generation also has problems on more recent Java versions, but at least I can run all ITs now.
=> Fix `alwaysOverwrite` IT on JDK 16 by upgrading to Groovy 3.0.8

README.md, src/it/alwaysOverwrite/verify.groovy, src/it/existingGetWithSignature/pom.xml, src/it/existingGetWithSignatureSha1/pom.xml, src/it/existingGetWithSignatureSha256/pom.xml, src/it/existingGetWithSignatureSha512/pom.xml, src/main/java/com/googlecode/download/maven/plugin/internal/ChecksumUtils.java, src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java, src/main/java/com/googlecode/download/maven/plugin/internal/cache/DownloadCache.java, src/main/java/com/googlecode/download/maven/plugin/internal/checksum/Checksum.java, src/main/java/com/googlecode/download/maven/plugin/internal/checksum/Checksums.java
Fixes #186, see the naming and documentation discussion there.
First, the plan was to just rename the one parameter and keep the one with the old name around as deprecated. while doing so, I noticed lots of
- class and package names,
- method names and parameters,
- javadocs and comments,
referring to digest-based checksums like SHA-1 and MD5 as "signatures" too, so I took care of globally renaming all of those too. That should make it easier to work with the code base in the future.
BTW, along the way I encountered the problem solved by #190, so maybe you want to merge than one first, if you like to run ITs on JDK 16 against this PR. Otherwise, the merge order does not matter.
=> Rename `checkSignature` to `alwaysVerifyChecksum`

.travis.yml, pom.xml
instead of https://github.com/maven-download-plugin/maven-download-plugin/pull/187
Had to bump invoker plugin version to make `streamLogsOnFailures` param work so we could see why travis build fails
=> bump http client version

src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java, src/main/java/com/googlecode/download/maven/plugin/internal/cache/DownloadCache.java, src/main/java/com/googlecode/download/maven/plugin/internal/cache/FileBackedIndex.java, src/main/java/com/googlecode/download/maven/plugin/internal/cache/IncompatibleIndexException.java, src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java
Changed the logic how we use the cache dir. The cache file is not created/written upon creation of the `FileIndex` object. Actually, that's not necessary, it's overwritten each time the `put` method is called.
I understand the reason why it was done like that was to spare other instances from running into the same problem. However, the very same index is going to be overwritten anyway if the plugin succeeds. It would be overwritten by another process anyway, if it finishes earlier. So it makes more sense to only write the cache upon ending and only lock the file for reading when the actual readable file is present in the first place.
Another problem was that the last process to write the changes to the cache overwrites all entries written to by previous processes.
Let's consider an …
=> #208: Don't try to write to cache until we exit gracefully

README.md, pom.xml, src/it-repo/dummy-api-1.0.jar, src/it-repo/dummy-api-1.0.pom, src/it-repo/dummy-dependency-1.0.jar, src/it-repo/dummy-dependency-1.0.pom, src/it-repo/dummy-impl-1.0.jar, src/it-repo/dummy-impl-1.0.pom, src/it/basicArtifact/invoke.properties, src/it/basicArtifact/pom.xml, src/it/basicArtifact/verify.groovy, src/it/basicArtifactTransitive/invoke.properties, src/it/basicArtifactTransitive/pom.xml, src/it/basicArtifactTransitive/verify.groovy, src/it/settings.xml, src/main/java/com/googlecode/download/maven/plugin/internal/ArtifactMojo.java, src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java, src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java, src/test/java/com/googlecode/download/maven/plugin/internal/HttpFileRequesterTest.java, src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java
Replacing Maven 2 APIs like ArtifactMetadataSource, ArtifactResolver, WagonManager, etc., with current, non-deprecated alternatives. Also, moving to JSR330 to be compliant with latest Maven standards and recommendations.
`Mojo`, `Artifact`: Class name changed to be in line with maven plugin naming conventions.
=> #224, #226: Replacing Maven 2 APIs with Maven 3

src/main/java/com/googlecode/download/maven/plugin/internal/ArtifactMojo.java
Alternative PR to #227 -- with added concurrency. There are basically no changes to what's been done in #227 except that I've also made it use the Java 8's CompletableFuture API.
It might be not as easy to review as the single threaded version ;) My preliminary tests show great performance improvements.
=> Resolves #230: Use concurrent calls in ArtifactMojo

src/it/GetAndUnpack/pom.xml, src/it/GetAndUnpackWithFileMapper/pom.xml, src/main/java/com/googlecode/download/maven/plugin/internal/DownloadFailureException.java, src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java, src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java, src/test/java/com/googlecode/download/maven/plugin/internal/HttpFileRequesterTest.java, src/test/java/com/googlecode/download/maven/plugin/internal/WGetMojoTest.java, src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java
This PR causes the plugin to fail (unless `failOnError` is `false`) upon a failed download attempt. With errors which can be transient, like 500, it's honoring the `retries` setting.
@longtimeago please check
=> Resolves #238: Handling download failures

src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java, src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java, src/main/java/com/googlecode/download/maven/plugin/internal/cache/FileBackedIndex.java, src/test/java/com/googlecode/download/maven/plugin/internal/WGetMojoTest.java, src/test/java/com/googlecode/download/maven/plugin/internal/cache/FileBackedIndexTest.java
- protected against the case when the user removes a file from cache
- flipped the default value of followRedirects
- removed the cached file size limit
- successful responses were being retried
@longtimeago please review
=> Fixing the broken release 1.7.0 #246

src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java
Prefixing uri.getHost() with uri.getScheme() + "://" in method createRemoteRepository when instantiating RemoteRepository.Builder so that property "host" will be populated on build.
When "host" is not populated, the correct proxy is not selected for the remote repository. Also modified method addProxy against NPE when ctx is null (no authentication needed)
=> Fix proxy support without authentication in wget

src/it/GetAndUnpackWhenChanged/invoke.properties, src/it/GetAndUnpackWhenChanged/pom.xml, src/it/GetAndUnpackWhenChanged/verify.groovy, src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java
Adds support for an `unpackWhenChanged` setting in the WGet goal, which will only unpack a downloaded file when it was not already present in the cache.
This is useful for executions which unpack downloads into non-transient directories (i.e. not `./target`) which only need subsequent unpacking when the source dependency archive changes.
=> Add support for wget unpackWhenChanged setting

pom.xml
plugin still works in 1.8 projects
=> rise java build requirement to v11 (due to mockito)

src/it/GetAndUnpackWhenChanged/pom.xml, src/it/reuseCacheFromOlderVersion/verify.groovy, src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java
If downloaded files are archives to be unpacked and files are cached, unpack the cached files directly instead of copying them to the outputFile path first. This saves time and storage and prevents strange behavior with the new unpackWhenChanged option (cached files were being copied to outputFile and then left there since the archives were not unpacked due to unchanged downloads).
=> Unpack directly from cached files when available

src/it/GetAndUnpackWhenChanged/invoke.properties, src/it/GetAndUnpackWhenChanged/verify.groovy, src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java
Small change to always unpack an unchanged cached archive if unpack is true, even if unpackWhenChanged is true. This allows users to force unpacking when the archives are cached/unchanged but the unpack target directory doesn't already contain the unpacked data (example Github Actions/CI builds).
=> Force unpack if unpack=true, even when unpackWhenChanged=true
