download-maven-plugin/download-maven-plugin

download-maven-plugin/pom.xml, download-maven-plugin/src/it/GetAndUnpack/pom.xml, download-maven-plugin/src/it/basicGet/pom.xml, download-maven-plugin/src/it/basicGetWithSignature/pom.xml, download-maven-plugin/src/it/basicGetWrongSignature/pom.xml
Fixed wrong artifact version in ITs and prevented futher mismatching
=> Fix version mismatch between main artifact and ITs

download-maven-plugin/pom.xml
PR for #41.
`mvn clean install` seemed to pass for me.
=> [#41] Bump Plexus Archiver to 3.0.1

download-maven-plugin/src/it/basicGetWithSignatureSha512/invoke.properties, download-maven-plugin/src/it/basicGetWithSignatureSha512/pom.xml, download-maven-plugin/src/it/basicGetWithSignatureSha512/verify.groovy, download-maven-plugin/src/main/java/com/googlecode/DownloadCache.java, download-maven-plugin/src/main/java/com/googlecode/SignatureUtils.java, download-maven-plugin/src/main/java/com/googlecode/WGet.java
Some sources which I download from only provied sha512 hashes. So I added support to compare also against sha512.
=> Added sha512 signature support for WGet

download-maven-plugin/src/it/basicGetWithSignatureSha1/invoke.properties, download-maven-plugin/src/it/basicGetWithSignatureSha1/pom.xml, download-maven-plugin/src/it/basicGetWithSignatureSha1/verify.groovy, download-maven-plugin/src/main/java/com/googlecode/DownloadCache.java, download-maven-plugin/src/main/java/com/googlecode/SignatureUtils.java, download-maven-plugin/src/main/java/com/googlecode/WGet.java
Now the sha512 support works - proven with the its-profile.
=> corrects SHA512 support

download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/ConsoleDownloadMonitor.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
@mickaelistria Hope, you will like it :)
=> #52 Refactor ConsoleDownloadManager to use maven logger instead of sout

download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/Artifact.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/CachedFileEntry.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/ConsoleDownloadMonitor.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/DownloadCache.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/SignatureUtils.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
Reformatted the code according to Java coding standards (reformatting only, nothing else)
@mickaelistria hope, you don't mind :)
=> Reformatted the code according to java coding standards

download-maven-plugin/pom.xml, download-maven-plugin/src/it/alwaysOverwrite/invoke.properties, download-maven-plugin/src/it/alwaysOverwrite/pom.xml, download-maven-plugin/src/it/alwaysOverwrite/verify.groovy, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
#75 Reproduced and fixed
@mickaelistria please, review
=> #75 Fix for non-overwriting the file if no signature specified,  skipCache and overwrite requested

download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/cache/DownloadCache.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/cache/FileBackedIndex.java, download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/cache/FileIndex.java, download-maven-plugin/src/test/java/com/googlecode/download/maven/plugin/internal/cache/FileBackedIndexTest.java
Changed URL -> URI
Maven understand URI well, so not a big deal
@mickaelistria Please, check if it's OK now
=> #79 Download URL now is URI in fact

download-maven-plugin/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
@mickaelistria can you review this?
=> Add download.plugin.skip.cache property to skipCache

.travis.yml, pom.xml
=> #131 Remove oraclejdk8 build from travis

src/it/basicGetWithSignatureSha256/invoke.properties, src/it/basicGetWithSignatureSha256/pom.xml, src/it/basicGetWithSignatureSha256/verify.groovy, src/it/basicGetWrongSignatureSha256/invoke.properties, src/it/basicGetWrongSignatureSha256/pom.xml, src/it/existingGetWithSignatureSha256/invoke.properties, src/it/existingGetWithSignatureSha256/pom.xml, src/it/existingGetWithSignatureSha256/prepare.groovy, src/it/existingGetWithSignatureSha256/verify.groovy, src/main/java/com/googlecode/download/maven/plugin/internal/SignatureUtils.java, src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java, src/main/java/com/googlecode/download/maven/plugin/internal/cache/DownloadCache.java
=> #135 Add support for SHA-256 signatures

src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
See: https://github.com/maven-download-plugin/maven-download-plugin/issues/142
=> Added missing property for some parameters.

src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
=> removed type check as it prevents any https proxies from working

src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java, src/main/java/com/googlecode/download/maven/plugin/internal/cache/DownloadCache.java, src/main/java/com/googlecode/download/maven/plugin/internal/signature/Signature.java, src/main/java/com/googlecode/download/maven/plugin/internal/signature/Signatures.java
fixes #161
fixes #112
Also if file is found in a cache only requested signatures are calculated (not all)
=> #161 Check all provided signatures on existing file with checkSignature = true

src/it/basicGetWithCustomHeaders/invoke.properties, src/it/basicGetWithCustomHeaders/pom.xml, src/it/basicGetWithCustomHeaders/verify.groovy, src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java, src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
Add a new parameter that allows users to specify custom http headers.
=> #8 Add support for HTTP headers

pom.xml, src/it/alwaysOverwrite/pom.xml, src/it/alwaysOverwrite/verify.groovy, src/it/basicGet/pom.xml, src/it/basicGetWithSignature/pom.xml, src/it/basicGetWithSignatureSha1/pom.xml, src/it/basicGetWithSignatureSha256/pom.xml, src/it/basicGetWithSignatureSha512/pom.xml, src/it/basicGetWrongSignature/pom.xml, src/it/basicGetWrongSignatureSha256/pom.xml, src/it/existingGetWithSignature/pom.xml, src/it/existingGetWithSignatureSha1/pom.xml, src/it/existingGetWithSignatureSha256/pom.xml, src/it/existingGetWithSignatureSha512/pom.xml, src/it/indexRetroCompatibility/pom.xml, src/it/it-test-parent/pom.xml, src/it/parallelRunOnlyAtRoot/pom.xml, src/it/parallelToSameFile/pom.xml
=> #170 fix broken link in ITs

src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
fixes #24
In offline mode the plugin gets a file from cache, otherwise fails
=> #24 Respect offline mode

src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java, src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
=> #174 Respect nonProxy host configuration

README.md
=> Configuration inside the execution is not read #108

src/it/basicGetWithRedirect/invoke.properties, src/it/basicGetWithRedirect/pom.xml, src/it/basicGetWithRedirect/verify.groovy, src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
=> Support Follow Redirects

src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
@fmotzkat could you, please, take a look?
=> #174 Another attempt to respect nonProxy host configuration

src/main/java/com/googlecode/download/maven/plugin/internal/SSLProtocols.java, src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
=> #182 Allow TLS1.3 communication of runtime supports it

src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
=> #185 Fix Unexpected "Ignoring download failure" warning message

pom.xml
=> #177 Bump maven-core dep to fix vulnerability in transitive dep com.google.guava:guava:25.1-android

pom.xml
=> #197 Bump plexus-archiver to fix vulnerability in org.apache.commons:commons-compress:1.20

src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
=> #199 Expand javadoc for overwrite and skipCache params

src/it/overwriteWithSkippedCache/invoke.properties, src/it/overwriteWithSkippedCache/pom.xml, src/it/overwriteWithSkippedCache/verify.groovy, src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
fixes #194
@vik4es would you be able to review the PR? :)
=> #194 Overwrite file if overwrite=true regardless of skipCache

src/it/basicGetWithQuery/invoke.properties, src/it/basicGetWithQuery/pom.xml, src/it/basicGetWithQuery/verify.groovy, src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
=> Fixed #204

src/it/GetAndUnpackWithFileMapper/invoke.properties, src/it/GetAndUnpackWithFileMapper/pom.xml, src/it/GetAndUnpackWithFileMapper/verify.groovy, src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java
=> [205] New <fileMappers> option

pom.xml, src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java, src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java
Not trying to deserialize the cache object from cache directory or write to cache directory if skipCache is true.
Plus a unit test.
=> Fixing #215: Don't try to read from or write to cache is skipCache is true

.github/workflows/maven.yml
Please integrate this so that we have CI flows running upon pull requests.
=> Added an example CI config

src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java
Moves MavenSession requirement into if block
=> Fixes #254  Moves requirement for MavenSession

.gitignore, pom.xml, src/it/GetAndUnpack/pom.xml, src/it/GetAndUnpackWithFileMapper/pom.xml, src/it/basicArtifact/pom.xml, src/it/basicArtifactTransitive/pom.xml, src/it/basicGet/pom.xml, src/it/indexRetroCompatibility/pom.xml, src/it/invokeWithBothServerIdAndUsername/pom.xml, src/it/invokeWithServerId/pom.xml, src/it/parallelRunOnlyAtRoot/pom.xml, src/it/parallelRunOnlyAtRoot/sub1/pom.xml, src/it/parallelRunOnlyAtRoot/sub2/pom.xml, src/it/parallelRunOnlyAtRoot/sub3/pom.xml, src/it/parallelRunOnlyAtRoot/sub4/pom.xml, src/it/parallelToSameFile/pom.xml, src/it/parallelToSameFile/sub1/pom.xml, src/it/parallelToSameFile/sub2/pom.xml, src/it/parallelToSameFile/sub3/pom.xml, src/it/parallelToSameFile/sub4/pom.xml
feel free to cherry-pick if too much at once.  I'm using maven 3.9.1 so not all items were put onto newer versions and still should be.
While all GH-Actions work, I'm using windows and before this 4 tests fail ITs and after 4 fail in slightly different way.  I can provide more detail on that if it is needed.
=> Bring maven up to date

pom.xml, src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java
=> #268 Fix broken file selector

.gitignore
may show up for Eclipse users, safe to ignore the file
=> [git] Add .factorypath to gitignore

src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java
Adds support for Maven's --no-transfer-progress/-ntp option, added in Maven 3.6.1.
https://maven.apache.org/docs/3.6.1/release-notes.html#user-visible-changes
Invocations with --no-transfer-progress/-ntp will not show download progress but will still have colorized output, in contrast to --batch-mode/-B which will suppress download progress but also remove colorization and other interactive mode features.
Closes #231
Fixes #273
=> Support Maven's --no-transfer-progress option

pom.xml
=> upgrade test deps

.tool-versions, pom.xml
=> #280 Rise required maven version to be at least 3.6.3

.github/workflows/release.yml, pom.xml
=> #282 Implement release procedure via Github workflow

README.md, pom.xml
=> #286 Turn back java 8 plugin compatibility

pom.xml, src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java, src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java
should resolve #264
Failed to find easy way of adding an IT here (without substituting MRM with something more controllable :/)
=> #264 Turn back support of encrypted passwords in maven settings.xml

checkstyle-suppressions.xml, src/main/java/com/googlecode/download/maven/plugin/internal/DownloadFailureException.java, src/main/java/com/googlecode/download/maven/plugin/internal/LoggingProgressReport.java, src/main/java/com/googlecode/download/maven/plugin/internal/cache/DownloadCache.java, src/main/java/com/googlecode/download/maven/plugin/internal/cache/FileBackedIndex.java
=> #291 Fix checkstyle violations (part 2)

checkstyle-suppressions.xml, src/main/java/com/googlecode/download/maven/plugin/internal/ArtifactMojo.java, src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java
=> #293 Fix checkstyle violations (part 3)

README.md, pom.xml, src/it/parallelRunOnlyAtRoot/verify.groovy, src/main/java/com/googlecode/download/maven/plugin/internal/ArtifactMojo.java, src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java, src/test/java/com/googlecode/download/maven/plugin/internal/WGetMojoTest.java
=> #248 Rename project according to Github org and repo renaming

checkstyle-ruleset.xml, src/main/java/com/googlecode/download/maven/plugin/internal/ArtifactMojo.java, src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java, src/main/java/com/googlecode/download/maven/plugin/internal/SSLProtocols.java, src/main/java/com/googlecode/download/maven/plugin/internal/checksum/Checksums.java
fixes #300
To avoid maven-javadoc-plugin crush on release
=> #300 Remove @checkstyle tags

pom.xml
=> #302 Avoid XmlStreamReader class not found on password decryption

checkstyle-suppressions.xml, src/main/java/com/googlecode/download/maven/plugin/internal/FilePermissions.java, src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java, src/test/java/com/googlecode/download/maven/plugin/internal/FilePermissionsTest.java, src/test/java/com/googlecode/download/maven/plugin/internal/WGetMojoTest.java
fixes #223
New configuration option available
```xml
<outputFilePermissions>+x</outputFilePermissions>
```
=> #223 An option to set executable permission on downloaded file

pom.xml
=> #305 Avoid "WARNING: A Java agent has been loaded dynamically" when running UTs
